### ISSUE TITLE
Reset sensor.values bzw event.values

### ISSUE THREAD

**Issue by pkhamkaew** [FabingoTH/MoCo_SoSe_2023#3]
Unser Sensor macht faxen, die Ballbewegungen sind dadurch fehlerhaft. Die Ballbewegungen sind nach dem Bauen der App perfekt, also versuchen wir, ob das Zurücksetzen der Koordinaten beim pausieren und beenden der App einen Unterschied macht

**Comment by C0d3GGz** [comment]
Der Sensor den Sie verwenden gibt zunächst nur die Rotation aus. Schauen Sie sich das [Bild in der Doku](https://developer.android.com/guide/topics/sensors/sensors_motion#sensors-motion-rotate) einmal an und achten Sie auf die Rohwerte während Sie das Smartphone drehen (ggf. müssen Sie das Koordinatensystem in Figure 1 gedanklich auch drehen). Damit wir aus den Sensordaten vernünftige "tilt-Werte" bekommen, müssen wir diese etwas anpassen, ggf. hilft nachfolgender Code

```Kotlin
val rotationMatrix = FloatArray(9)
SensorManager.getRotationMatrixFromVector(rotationMatrix, event.values)

// Remap the coordinate system to align with the device's orientation
val remappedRotationMatrix = FloatArray(9)
SensorManager.remapCoordinateSystem(
    rotationMatrix,
    SensorManager.AXIS_X, SensorManager.AXIS_Y, remappedRotationMatrix
)

// Extract the orientation angles from the remapped rotation matrix
val orientationAngles = FloatArray(3)
SensorManager.getOrientation(remappedRotationMatrix, orientationAngles)

// Calculate the tilt angle around the X-axis (pitch)
xTilt = -orientationAngles[1]
yTilt = -orientationAngles[2]
updateCoordinates()
```

Als Rotationsmatrix reicht eine Größe von 9, siehe Dokumentation von `getRotationMatrixFromVector`

**Comment by pkhamkaew** [comment]
Danke dafür! Das funktioniert jetzt bei uns.
